// OpenAPI annotations on route schemas. `@fastify/swagger` normally adds these
// to `FastifySchema`, but it is a build-time devDependency now (the OpenAPI
// document is generated by scripts/generate-openapi.mjs), so the hub declares
// the two fields its routes use itself and never imports the plugin.
declare module 'fastify' {
  interface FastifySchema {
    summary?: string;
    tags?: readonly string[];
  }
}

export {};
